### PR TITLE
Add navigation events to history plugin.

### PR DESCRIPTION
**Pull request by natecox**
This is a small update that adds an event to the `goForward` and `goBack` methods of the history plugin, so that listening applications can act appropriately on viewed image change if needed.

Note: I initially thought to use use `image:change` instead of creating a new event, but it caused cyclical calls to the internal method of popping content onto the history stack.

### CODE REVIEW

**Comment by natecox** [comment]
I've also removed /build from the ignore lists for git and bower. In order for this library to be viable for distribution on Bower you should have immediate access to the CSS and JS needed to run the project, rather than have to build it yourself.

**Comment by MattKetmo** [comment]
Hello. Sorry for the delay, I've merged your PR with 55b4ab9 + b65ff65.
Thank you.

**Comment by MattKetmo** [comment]
Btw, is there a reason to downgrade the version in the `bower.json`?

**Comment by natecox** [comment]
I actually published my fork to bower temporarily so that I could use the changes I made and lowered the version to make a clear distinction. Should definitely be bumped back up.

**Pull request closed without merging**
