### PR TITLE
Overlay should be one polygon

### PR DESCRIPTION
**Pull request by jacksonhoose**
Fixes hairline issue where previous rectangles were meeting.  This makes overlay 1 solid shape and gets rid of hairlines.

### CODE REVIEW

**Comment by marcelgruber** [comment]
Is this related to this issue? https://github.com/MattKetmo/darkroomjs/issues/66

**Comment by jacksonhoose** [comment]
@marcelgruber Not entirely sure, but updated PR to include a fix for the edges of the overlay sometimes getting blurry when the selection is being scaled.

**Comment by jacksonhoose** [comment]
@marcelgruber sounds like #68 refers to saving. This PR addresses the overlay's appearance.

**Comment by MattKetmo** [comment]
Thanks. This is much more clever :+1:

**Pull request merged**
