### PR TITLE
Update darkroom.rotate.js

### PR DESCRIPTION
**Pull request by oceanwap**
Better Image rotation for angles less than 90

### CODE REVIEW

**Comment by MattKetmo** [comment]
Thanks.

**Comment by oceanwap** [comment]
Thanks Matthieu.
I will continue to contribute.

**Comment by oceanwap** [comment]
Hi,

I&#39;d like to add you to my professional network on LinkedIn.

- Roshan

Accept: https://www.linkedin.com/blink?simpleRedirect=0UczcVdP4Oe3kNcjsRcP0MdPARfkh9rCZFt65QqnpKqioMlD58jCRIljRVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9D4ObmtOcjxTtzlFbnFMs69GoPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970035746378129408_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=sj8JpT8Ne7tSdmAJuD1MoCFzfmhFpipOk5wRh5hat3d8u3t7iBZ4skFbjzlTiP0JkQxjpltaoCFFj3xClk5jimZ5onEJqkB2cR9mhntAsnBTozxPs7gTqAZWjCkVujpggAdzoCJPoAlRiCV5dT1MoAESoSQPunFIdkVUgQVRl4F6p55WlnhRiT53gAlWrQ5EcDBfr753q4ESekhMpSV1q5d5uz5mh64UhkROk7hQr2RDjBZgp6lFe311qmpNgSBUp4dNunwSl6VQlk51gk5cd6V5hBBgdPBnhl51fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9D4ObmtOcjxTtzlFbnFMs69GoPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5970035746378129408_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9D4ObmtOcjxTtzlFbnFMs69GoPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970035746378129408_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by oceanwap** [comment]
Roshan Kumar would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0UczcVdP4Oe3kNcjsRcP0MdPARfkh9rCZFt65QqnpKqioMlD58jCRIljRVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CsRbnhztD8OuzlFbnFMs69GoPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970035746378129408_500&markAsRead=

View Roshan Kumar&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9CsRbnhztD8OuzlFbnFMs69GoPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970035746378129408_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9jtBozlAd3cMpmcVdz5xczAPd6pCe6kMcj4Mc30Mc30MpCcOem4QojBxcjtCpCdCdz5AdPlCd3wNpz5ypjlAcz8MoP9xe3hzozlAozkRoj4VoP0Mc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9zwOcPATcj8Udj4NdPkPc30TejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9CsRbnhztD8OuzlFbnFMs69GoPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970035746378129408_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1DdiRQoTpOcDERqiRWs71yqCcZp6BB9zBfrnpzcyQNl4ENgkliiBhoiPhHjnh6l7oUczpcoz9ic7dAqnxeqCRSsQtQc7oSm55qtlpKpAl5hQhogCVOk3xep4lQkDh5pPBDnP9fcldpd753eklliB4JlQZogQJRqn9olBlbe65er7xqrQVlm45Li4xchzlVdTgVr4xhrz9Sl6x6rA4TdRxPgTBqgB12ln9ciClRmD5ju6UPrCRTmm8Mhzt1hBtkojxcrlgQjP9Uunhlgk51gj9CnR9hh54RmDB6kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CsRbnhztD8OuzlFbnFMs69GoPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5970035746378129408_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CsRbnhztD8OuzlFbnFMs69GoPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970035746378129408_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by oceanwap** [comment]
Roshan Kumar would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0UczcVdP4Oe3kNcjsRcP0MdPARfkh9rCZFt65QqnpKqioMlD58jCRIljRVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9z8Nbj4PsClNdPpFbnFMs69GoPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970035746378129408_500&markAsRead=

View Roshan Kumar&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9z8Nbj4PsClNdPpFbnFMs69GoPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970035746378129408_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9jtBozlAd3cMpmcVdz5xczAPd6pCe6kMcj4Mc30Mc30MpCcOem4QojBxcjtCpCdCdz5AdPlCd3wNpz5ypjlAcz8MoP9xe3hzozlAozkRoj4VoP0Mc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9zwOcPATcj8Udj4NdPkPc30TejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9z8Nbj4PsClNdPpFbnFMs69GoPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970035746378129408_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=0OciQNcT9BsjsSqiRWs71yqCcZp6BB9BZQlAhlemYJl3dHh6J1rnlFi7l6sC54jPx1ckdWrPxEkCR9jT5elDkOhzxKi6dbk6JBll9WdPoNlD13d6pUlTx3rAlJojpqjlpWon9TtnkPsRgNc3dggRgTs6VooCBUpSFLr4F1rRl3dzpVpTAQsA99tklTikRSjlsVikdaonFnoAxorlBjlDdKtn0Nt5hvm7Fvk5x8m711ej1nqCJPgDdPuCljcl52d4MRsB53emUJkDllgk51tTBjhl5amD9fpSB7kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9z8Nbj4PsClNdPpFbnFMs69GoPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5970035746378129408_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9z8Nbj4PsClNdPpFbnFMs69GoPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5970035746378129408_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Pull request merged**
